/**
 * %% Copyright (C) 2021 DataScience 9 LLC %% Licensed under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the License. You may obtain a
 * copy of the License at
 *
 * <p>http://www.apache.org/licenses/LICENSE-2.0
 *
 * <p>Unless required by applicable law or agreed to in writing, software distributed under the
 * License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing permissions and
 * limitations under the License. #L%
 *
 * <p>This code is 100% AUTO generated. Please do not modify it DIRECTLY If you need new features or
 * function or changes please update the templates then submit the template through our web
 * interface.
 */
package com.sportsdb.test.utils;

public enum MetaDataEnum {
    Addresses,
    AffiliationPhases,
    Affiliations,
    AffiliationsDocuments,
    AffiliationsEvents,
    AffiliationsMedia,
    AmericanFootballActionParticipants,
    AmericanFootballActionPlays,
    AmericanFootballDefensiveStats,
    AmericanFootballDownProgressStats,
    AmericanFootballEventStates,
    AmericanFootballFumblesStats,
    AmericanFootballOffensiveStats,
    AmericanFootballPassingStats,
    AmericanFootballPenaltiesStats,
    AmericanFootballRushingStats,
    AmericanFootballSacksAgainstStats,
    AmericanFootballScoringStats,
    AmericanFootballSpecialTeamsStats,
    BaseballActionContactDetails,
    BaseballActionPitches,
    BaseballActionPlays,
    BaseballActionSubstitutions,
    BaseballDefensiveGroup,
    BaseballDefensivePlayers,
    BaseballDefensiveStats,
    BaseballEventStates,
    BaseballOffensiveStats,
    BaseballPitchingStats,
    BasketballDefensiveStats,
    BasketballEventStates,
    BasketballOffensiveStats,
    BasketballReboundingStats,
    BasketballTeamStats,
    Bookmakers,
    CorePersonStats,
    CoreStats,
    DbInfo,
    DisplayNames,
    DocumentClasses,
    DocumentContents,
    DocumentFixtures,
    DocumentFixturesEvents,
    DocumentPackageEntry,
    DocumentPackages,
    Documents,
    DocumentsMedia,
    Events,
    EventsDocuments,
    EventsMedia,
    EventsSubSeasons,
    IceHockeyActionParticipants,
    IceHockeyActionPlays,
    IceHockeyDefensiveStats,
    IceHockeyEventStates,
    IceHockeyOffensiveStats,
    IceHockeyPlayerStats,
    InjuryPhases,
    KeyAliases,
    KeyRoots,
    LatestRevisions,
    Locations,
    Media,
    MediaCaptions,
    MediaContents,
    MediaKeywords,
    MotorRacingEventStates,
    MotorRacingQualifyingStats,
    MotorRacingRaceStats,
    OutcomeTotals,
    ParticipantsEvents,
    Periods,
    PersonEventMetadata,
    PersonPhases,
    Persons,
    PersonsDocuments,
    PersonsMedia,
    Positions,
    Publishers,
    Roles,
    Seasons,
    Sites,
    SoccerDefensiveStats,
    SoccerEventStates,
    SoccerFoulStats,
    SoccerOffensiveStats,
    StandingSubgroups,
    Standings,
    Stats,
    SubPeriods,
    SubSeasons,
    TeamAmericanFootballStats,
    TeamPhases,
    Teams,
    TeamsDocuments,
    TeamsMedia,
    TennisActionPoints,
    TennisActionVolleys,
    TennisEventStates,
    TennisReturnStats,
    TennisServiceStats,
    WageringMoneylines,
    WageringOddsLines,
    WageringRunlines,
    WageringStraightSpreadLines,
    WageringTotalScoreLines,
    WeatherConditions,
}
